###########
# site.title

title:    'fiug.dev'
subtitle: 'the blog'

description: blogging about fiug.dev project
author: Harrison Cross
permalink: none
# permalink: /:year/:month/:day/:title:output_ext

version:
  beta: 0.4.4
  prod: 0.4.3
  
# collections_dir: ../

nav:
# - { title: 'Welcome',              href: '/' }
- { title: 'Present',             href: '/present/' }
- { title: 'Planned',             href: '/planned/' }
- { title: 'Released',           href: '/released/' }
- { title: 'Random',             href: '/random/' }
- { title: '@github', href: 'https://github.com/crosshj/fiug-blog/tree/main/docs' }


defaults:
  -
    scope:
      path: "" # all project files
      type: "posts" # of post type
    values:
      layout: "post"
      excerpt_separator: <!-- more -->

collections:
  releases:
    layout: "post"
    output: true


#########################
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

assets:
  sources:
    - images

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

highlighter: rouge

plugins:
  - jekyll-feed

