###########
# site.title

title:    'fiug.dev'
subtitle: ''


nav:
# - { title: 'Welcome',              href: '/' }
- { title: 'Page Two',             href: '/two.html' }
- { title: 'Page Three',           href: '/three.html' }


#########################
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

assets:
  sources:
    - images

exclude:
- README.md
- LICENSE.md

