###########
# site.title

title:    'fiug.dev'
subtitle: ''


nav:
# - { title: 'Welcome',              href: '/' }
- { title: 'Present',             href: '/two.html' }
- { title: 'Planned',             href: '/two.html' }
- { title: 'Released',           href: '/three.html' }
- { title: 'Random',             href: '/two.html' }

#########################
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

assets:
  sources:
    - images

exclude:
  - README.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock

gems:
  - jekyll-feed
  - jekyll-assets

include: [_posts]
