###########
# site.title

title:    'fiug.dev'
subtitle: ''

description: blogging about fiug.dev project
author: Harrison Cross
permalink: /:year/:month/:day/:title:output_ext

nav:
# - { title: 'Welcome',              href: '/' }
- { title: 'Present',             href: '/two.html' }
- { title: 'Planned',             href: '/two.html' }
- { title: 'Released',           href: '/three.html' }
- { title: 'Random',             href: '/two.html' }

#########################
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

assets:
  sources:
    - images

exclude:
  - README.md
  - LICENSE.md

highlighter: rouge

plugins:
  - jekyll-feed

