###########
# site.title

title:    'fiug.dev'
subtitle: 'the blog'

description: blogging about fiug.dev project
author: Harrison Cross
permalink: /:year/:month/:day/:title:output_ext

nav:
# - { title: 'Welcome',              href: '/' }
- { title: 'Present',             href: '/present/' }
- { title: 'Planned',             href: '/planned/' }
- { title: 'Released',           href: '/released/' }
- { title: 'Random',             href: '/random/' }
- { title: '@github', href: 'https://github.com/crosshj/fiug-blog' }

#########################
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

assets:
  sources:
    - images

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

highlighter: rouge

plugins:
  - jekyll-feed

